version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: "/"
    pattern: ""
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: start_server.sh
      timeout: 10
      runas: root
