version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x # Specify the Node.js version
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      -
      - mkdir test1
      - echo Build completed.

artifacts:
  files:
    # - node_modules/**/*
    # - build/**/*
    - appspec.yml
    - buildspec.yml
    - install_dependencies.sh
    - start_server.sh
    # - '**/*'

  discard-paths: yes

cache:
  paths:
    - node_modules/**/*

env:
  variables:
    REACT_APP_ENV: "production" # Example of setting an environment variable
